language: node_js

node_js:
  - 'stable'
  - '0.12'

# Support for Google Chrome.
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: node_modules/karma/bin/karma start karma.conf.js --single-run

after_success:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < reports/coverage/report-lcov/lcov.info
